# 参考说明：此配置的国内转发策略比较激进只走quic ali 
# 有需要请在forward_cn中添加其他解析服务器（如运营商dns等）
# 有一些其他网段的转发策略，如dn11，dn42，hdu等，不需要请删除

log:
  level: info
  file: "/tmp/mosdns.log"

# api:
#   http: "127.0.0.1:9091" # 在该地址启动 api 接口。

# 如下的/usr/share/passwall等是passwall拉取自动更新的文件，可以自行替换为自己的文件

plugins:
  # 白名单 加入的域名始终允许使用 “本地 DNS” 进行解析
  - tag: whitelist
    type: domain_set
    args:
      files:                        # 从文本文件载入
        - "/etc/mosdns/rule/whitelist.txt"
        - "/usr/share/passwall/rules/chnlist"

  # 黑名单 加入的域名将通过clash分流
  - tag: proxylist
    type: domain_set
    args:
      files:                        # 从文本文件载入
        - "/etc/mosdns/rule/blocklist.txt"
        - "/usr/share/passwall/rules/gfwlist"

  # 强制黑名单 加入的域名将通过clash分流
  - tag: proxylist_force
    type: domain_set
    args:
      files:                        # 从文本文件载入
        - "/etc/mosdns/rule/blocklist.txt"

  # 双栈白名单
  - tag: duallist
    type: domain_set
    args:
      files:                        # 从文本文件载入
        - "/etc/mosdns/rule/greylist.txt"

  # 自定义 Hosts 重写
  - tag: hosts
    type: hosts
    args:
      files:                        # 从文本文件载入
        - "/etc/mosdns/rule/hosts.txt"

  # 重定向请求的域名
  - tag: redirect
    type: redirect
    args:
      files:
        - "/etc/mosdns/rule/redirect.txt"

#  # 缓存
#  - tag: cache
#    type: cache
#    args:
#      size: 102400
#      lazy_cache_ttl: 0
#      dump_file: "/etc/mosdns/rule/cache.dump"
#      dump_interval: 3600

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # 转发至本地服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "quic://dns.alidns.com"


  - tag: forward_cn
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "quic://dns.alidns.com"

#        - addr: tcp://202.101.172.46
#          enable_pipeline: true
#        - addr: tcp://223.6.6.6
#          enable_pipeline: true
#        - addr: tls://dns.alidns.com
          bootstrap: "172.16.3.2"
#          enable_pipeline: true
#        - addr: tls://dot.pub
#          bootstrap: "172.16.3.2"
#          enable_pipeline: true

  # 转发至远程服务器
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: tls://8.8.8.8:853
          enable_pipeline: true
        - addr: tls://1.1.1.1:853
          enable_pipeline: true

  # 转发至clashdns
  - tag: clash_remote
    type: forward
    args:
      upstreams:
        - addr: 127.0.0.1:7874

  # 转发至dn11
  - tag: dn11_remote
    type: forward
    args:
      upstreams:
        - addr: 172.16.255.53:53

  # 转发至dn42
  - tag: dn42_remote
    type: forward
    args:
      upstreams:
        - addr: 172.20.0.53:53

  # 转发至hdu
  - tag: hdu_remote
    type: forward
    args:
      upstreams:
        - addr: 192.168.101.249:53

  # 国内解析
  - tag: local_sequence
    type: sequence
    args:
#      - exec: $cache
      - exec: jump has_resp_sequence
      - exec: $forward_local

  # 国内解析
  - tag: cn_sequence
    type: sequence
    args:
#      - exec: $cache
      - exec: jump has_resp_sequence
      - matches:  "!qname $duallist"
        exec:  prefer_ipv4
      - exec: $forward_cn

  # 国外解析
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote

  # clash解析
  - tag: fakeip_sequence
    type: sequence
    args:
      - exec: $clash_remote
      - exec: ttl 60-0

  # dn11解析
  - tag: dn11_sequence
    type: sequence
    args:
      - exec: $dn11_remote

  # dn42解析
  - tag: dn42_sequence
    type: sequence
    args:
      - exec: $dn42_remote

  # hdu解析
  - tag: hdu_sequence
    type: sequence
    args:
      - exec: $hdu_remote

  # 查询chnlist
  - tag: query_is_whitelist_domain
    type: sequence
    args:
      - matches: qname $whitelist
        exec: $cn_sequence

  # 查询proxylist
  - tag: query_is_proxy_domain
    type: sequence
    args:
      - matches: qname $proxylist
        exec: $fakeip_sequence

  # 查询proxylist_force
  - tag: query_is_proxy_domain_force
    type: sequence
    args:
      - matches: qname $proxylist_force
        exec: $fakeip_sequence

  # 查询未知域名
  - tag: query_is_unknown_domain
    type: sequence
    args:
      - exec: $cn_sequence
      # - matches: "!resp_ip $geoip_cn"
      #  exec: drop_resp

  # 查询dn11
  - tag: query_is_dn11_domain
    type: sequence
    args:
      - matches: qname domain:dn11
        exec: $dn11_sequence

  # 查询dn42
  - tag: query_is_dn42_domain
    type: sequence
    args:
      - matches: qname domain:dn42
        exec: $dn42_sequence

  # 查询hdu
  - tag: query_is_hdu_domain
    type: sequence
    args:
      - matches: qname domain:hdu.edu.cn
        exec: $hdu_sequence

  # 查询非A和AAAA记录
  - tag: query_is_not_aaaa_a
    type: sequence
    args:
      - matches: "!qtype 1 28"
        exec: $local_sequence

  # 阻止Https类型
  - tag: query_is_https
    type: sequence
    args:
      - matches: qtype 65
        exec: reject 0

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - exec: $query_is_https
      - exec: jump has_resp_sequence
      - exec: $query_is_not_aaaa_a
      - exec: jump has_resp_sequence
      - exec: $hosts
      - exec: jump has_resp_sequence
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_proxy_domain_force
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_dn11_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_dn42_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_hdu_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_proxy_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_unknown_domain
      - exec: jump has_resp_sequence
      - exec: $remote_sequence

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"

  - tag: udp_server_2
    type: udp_server
    args:
      entry: main_sequence
      listen: "172.16.3.13:53"